Update workflow.yml

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -125,6 +125,13 @@ jobs:
         brew update
         brew install cmake sdl2 sdl2_mixer sdl2_image sdl2_ttf jansson
         pip install sphinx
+
+    - name: Verify Sentry Header Exists
+      run: |
+        if [ ! -f "${{ github.workspace }}/libs/CrashRpt/install/include/sentry.h" ]; then
+          echo "sentry.h not found!"
+          exit 1
+        fi
         
     - name: Diagnose Include Paths
       run: >
@@ -133,6 +140,7 @@ jobs:
         -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
         -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
         -DCMAKE_VERBOSE_MAKEFILE=ON
+        -DUSE_SENTRY=ON
         -DSENTRY_INCLUDE_DIR=libs/CrashRpt/install/include/
         -S ${{ github.workspace }}
         -LAH
@@ -146,6 +154,7 @@ jobs:
         -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
         -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
         -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
+        -DUSE_SENTRY=OFF
         -DCMAKE_VERBOSE_MAKEFILE=ON
         -S ${{ github.workspace }}
 
